import { Clinic } from "@/types";

export const SEED_CLINICS: Omit<Clinic, "created_at">[] = [
  {
    id: "1",
    clinic_name: "Aruba Primary Health Centre",
    lga: "Sagamu",
    ward: "Sabo Agura",
    town: "Sagamu",
    address: "Sabo Agura Ward, Sagamu, Ogun State",
    latitude: 6.825422,
    longitude: 3.655275,
    phone: "08012345601",
    opening_hours: "Mon–Fri: 8:00am – 4:00pm",
    services: ["TB Screening", "DOT Treatment", "General OPD"],
    genexpert_available: false,
    hiv_tb_integrated: true,
    pediatric_tb: false,
    drug_refill_days: "Mondays and Thursdays",
    contact_officer: "Nurse Adebayo",
    whatsapp_number: "2348012345601",
    facility_location_type: "Semi-Urban",
    status: "active",
  },
  {
    id: "2",
    clinic_name: "Emuren Primary Health Centre",
    lga: "Sagamu",
    ward: "Odelemo",
    town: "Emuren",
    address: "Odelemo Ward, Emuren, Sagamu LGA, Ogun State",
    latitude: 6.696772,
    longitude: 3.617214,
    phone: "08012345602",
    opening_hours: "Mon–Fri: 8:00am – 4:00pm",
    services: ["TB Screening", "DOT Treatment"],
    genexpert_available: false,
    hiv_tb_integrated: false,
    pediatric_tb: false,
    drug_refill_days: "Tuesdays",
    contact_officer: "CHO Oluwaseun",
    whatsapp_number: "2348012345602",
    facility_location_type: "Rural",
    status: "active",
  },
  {
    id: "3",
    clinic_name: "Itunsoku Primary Health Centre",
    lga: "Sagamu",
    ward: "Itunsoku",
    town: "Sagamu",
    address: "Itunsoku Ward, Sagamu, Ogun State",
    latitude: 6.841372,
    longitude: 3.646416,
    phone: "08012345603",
    opening_hours: "Mon–Fri: 8:00am – 5:00pm",
    services: ["TB Screening", "DOT Treatment", "HIV/TB Clinic"],
    genexpert_available: true,
    hiv_tb_integrated: true,
    pediatric_tb: true,
    drug_refill_days: "Mondays, Wednesdays and Fridays",
    contact_officer: "Dr. Akinwale",
    whatsapp_number: "2348012345603",
    facility_location_type: "Urban",
    status: "active",
  },
  {
    id: "4",
    clinic_name: "Sabo GRA Health Centre",
    lga: "Sagamu",
    ward: "Sabo GRA",
    town: "Sagamu",
    address: "Sabo GRA, Sagamu, Ogun State",
    latitude: 6.836423,
    longitude: 3.633725,
    phone: "08012345604",
    opening_hours: "Mon–Fri: 8:00am – 4:00pm",
    services: ["TB Screening", "DOT Treatment", "General OPD"],
    genexpert_available: false,
    hiv_tb_integrated: false,
    pediatric_tb: false,
    drug_refill_days: "Fridays",
    contact_officer: "Nurse Folake",
    whatsapp_number: "2348012345604",
    facility_location_type: "Urban",
    status: "active",
  },
  {
    id: "5",
    clinic_name: "Sabo Agura PHC",
    lga: "Sagamu",
    ward: "Sabo Agura",
    town: "Sagamu",
    address: "Sabo Agura, Sagamu, Ogun State",
    latitude: 6.832458,
    longitude: 3.647943,
    phone: "08012345605",
    opening_hours: "Mon–Sat: 8:00am – 4:00pm",
    services: ["TB Screening", "DOT Treatment", "Pediatric TB"],
    genexpert_available: false,
    hiv_tb_integrated: true,
    pediatric_tb: true,
    drug_refill_days: "Tuesdays and Fridays",
    contact_officer: "CHO Bamidele",
    whatsapp_number: "2348012345605",
    facility_location_type: "Urban",
    status: "active",
  },
  {
    id: "6",
    clinic_name: "Afisuru Health Centre",
    lga: "Sagamu",
    ward: "Ogijo",
    town: "Ogijo",
    address: "Ogijo Ward, Sagamu LGA, Ogun State",
    latitude: 6.716394,
    longitude: 3.521219,
    phone: "08012345606",
    opening_hours: "Mon–Fri: 8:00am – 4:00pm",
    services: ["TB Screening", "DOT Treatment"],
    genexpert_available: false,
    hiv_tb_integrated: false,
    pediatric_tb: false,
    drug_refill_days: "Mondays",
    contact_officer: "Nurse Kehinde",
    whatsapp_number: "2348012345606",
    facility_location_type: "Semi-Urban",
    status: "active",
  },
  {
    id: "7",
    clinic_name: "Ogijo Health Centre",
    lga: "Sagamu",
    ward: "Ogijo",
    town: "Ogijo",
    address: "Ogijo, Sagamu LGA, Ogun State",
    latitude: 6.70418,
    longitude: 3.511011,
    phone: "08012345607",
    opening_hours: "Mon–Fri: 8:00am – 5:00pm",
    services: ["TB Screening", "DOT Treatment", "HIV/TB Clinic", "GeneXpert"],
    genexpert_available: true,
    hiv_tb_integrated: true,
    pediatric_tb: false,
    drug_refill_days: "Mondays, Wednesdays",
    contact_officer: "Dr. Omotola",
    whatsapp_number: "2348012345607",
    facility_location_type: "Urban",
    status: "active",
  },
  {
    id: "8",
    clinic_name: "Ajegunle Primary Health Centre",
    lga: "Sagamu",
    ward: "Ogijo",
    town: "Ajegunle",
    address: "Ajegunle, Ogijo, Sagamu LGA, Ogun State",
    latitude: 6.692734,
    longitude: 3.494852,
    phone: "08012345608",
    opening_hours: "Mon–Fri: 8:00am – 3:00pm",
    services: ["TB Screening", "DOT Treatment"],
    genexpert_available: false,
    hiv_tb_integrated: false,
    pediatric_tb: false,
    drug_refill_days: "Thursdays",
    contact_officer: "CHO Adewale",
    whatsapp_number: "2348012345608",
    facility_location_type: "Rural",
    status: "active",
  },
  {
    id: "9",
    clinic_name: "Ogede Health Post",
    lga: "Sagamu",
    ward: "Ogijo",
    town: "Ogede",
    address: "Ogede Village, Ogijo, Sagamu LGA, Ogun State",
    latitude: 6.716801,
    longitude: 3.481645,
    phone: "08012345609",
    opening_hours: "Mon, Wed, Fri: 8:00am – 2:00pm",
    services: ["TB Screening", "DOT Treatment"],
    genexpert_available: false,
    hiv_tb_integrated: false,
    pediatric_tb: false,
    drug_refill_days: "Wednesdays",
    contact_officer: "Nurse Bello",
    whatsapp_number: "2348012345609",
    facility_location_type: "Rural",
    status: "active",
  },
  {
    id: "10",
    clinic_name: "Aiyegbami Primary Health Centre",
    lga: "Sagamu",
    ward: "Aiyegbami",
    town: "Sagamu",
    address: "Aiyegbami Ward, Sagamu, Ogun State",
    latitude: 6.837634,
    longitude: 3.652595,
    phone: "08012345610",
    opening_hours: "Mon–Fri: 8:00am – 4:00pm",
    services: ["TB Screening", "DOT Treatment", "General OPD"],
    genexpert_available: false,
    hiv_tb_integrated: true,
    pediatric_tb: false,
    drug_refill_days: "Tuesdays",
    contact_officer: "CHO Olamide",
    whatsapp_number: "2348012345610",
    facility_location_type: "Urban",
    status: "active",
  },
  {
    id: "11",
    clinic_name: "Batoro Primary Health Centre",
    lga: "Sagamu",
    ward: "Batoro",
    town: "Sagamu",
    address: "Batoro Ward, Sagamu, Ogun State",
    latitude: 6.844058,
    longitude: 3.650475,
    phone: "08012345611",
    opening_hours: "Mon–Fri: 8:00am – 4:00pm",
    services: ["TB Screening", "DOT Treatment"],
    genexpert_available: false,
    hiv_tb_integrated: false,
    pediatric_tb: false,
    drug_refill_days: "Mondays",
    contact_officer: "Nurse Taiwo",
    whatsapp_number: "2348012345611",
    facility_location_type: "Urban",
    status: "active",
  },
  {
    id: "12",
    clinic_name: "Ipoji Primary Health Centre",
    lga: "Sagamu",
    ward: "Ipoji",
    town: "Sagamu",
    address: "Ipoji Ward, Sagamu, Ogun State",
    latitude: 6.845309,
    longitude: 3.652082,
    phone: "08012345612",
    opening_hours: "Mon–Fri: 8:00am – 4:00pm",
    services: ["TB Screening", "DOT Treatment"],
    genexpert_available: false,
    hiv_tb_integrated: false,
    pediatric_tb: true,
    drug_refill_days: "Wednesdays",
    contact_officer: "CHO Sola",
    whatsapp_number: "2348012345612",
    facility_location_type: "Urban",
    status: "active",
  },
  {
    id: "13",
    clinic_name: "Legacy Health Centre",
    lga: "Sagamu",
    ward: "Soyindo",
    town: "Sagamu",
    address: "Soyindo Ward, Sagamu, Ogun State",
    latitude: 6.852567,
    longitude: 3.654561,
    phone: "08012345613",
    opening_hours: "Mon–Fri: 8:00am – 4:00pm",
    services: ["TB Screening", "DOT Treatment", "HIV/TB Clinic"],
    genexpert_available: false,
    hiv_tb_integrated: true,
    pediatric_tb: false,
    drug_refill_days: "Thursdays",
    contact_officer: "Nurse Comfort",
    whatsapp_number: "2348012345613",
    facility_location_type: "Urban",
    status: "active",
  },
  {
    id: "14",
    clinic_name: "Agbowa Ibido Health Centre",
    lga: "Sagamu",
    ward: "Agbowa",
    town: "Agbowa",
    address: "Agbowa Ibido, Sagamu LGA, Ogun State",
    latitude: 6.851995,
    longitude: 3.647027,
    phone: "08012345614",
    opening_hours: "Mon–Fri: 8:00am – 4:00pm",
    services: ["TB Screening", "DOT Treatment"],
    genexpert_available: false,
    hiv_tb_integrated: false,
    pediatric_tb: false,
    drug_refill_days: "Fridays",
    contact_officer: "CHO Gboyega",
    whatsapp_number: "2348012345614",
    facility_location_type: "Urban",
    status: "active",
  },
  {
    id: "15",
    clinic_name: "Ajaka Primary Health Centre",
    lga: "Sagamu",
    ward: "Ajaka",
    town: "Sagamu",
    address: "Ajaka Ward, Sagamu, Ogun State",
    latitude: 6.853548,
    longitude: 3.635688,
    phone: "08012345615",
    opening_hours: "Mon–Fri: 8:00am – 4:00pm",
    services: ["TB Screening", "DOT Treatment", "Pediatric TB"],
    genexpert_available: false,
    hiv_tb_integrated: false,
    pediatric_tb: true,
    drug_refill_days: "Mondays",
    contact_officer: "Nurse Blessing",
    whatsapp_number: "2348012345615",
    facility_location_type: "Urban",
    status: "active",
  },
  {
    id: "16",
    clinic_name: "Ijagba Health Centre",
    lga: "Sagamu",
    ward: "Ijagba",
    town: "Sagamu",
    address: "Ijagba Ward, Sagamu, Ogun State",
    latitude: 6.847589,
    longitude: 3.645721,
    phone: "08012345616",
    opening_hours: "Mon–Fri: 8:00am – 4:00pm",
    services: ["TB Screening", "DOT Treatment"],
    genexpert_available: false,
    hiv_tb_integrated: false,
    pediatric_tb: false,
    drug_refill_days: "Tuesdays",
    contact_officer: "CHO Segun",
    whatsapp_number: "2348012345616",
    facility_location_type: "Urban",
    status: "active",
  },
  {
    id: "17",
    clinic_name: "Latawa Primary Health Centre",
    lga: "Sagamu",
    ward: "Latawa",
    town: "Sagamu",
    address: "Latawa Ward, Sagamu, Ogun State",
    latitude: 6.844648,
    longitude: 3.644424,
    phone: "08012345617",
    opening_hours: "Mon–Fri: 8:00am – 4:00pm",
    services: ["TB Screening", "DOT Treatment"],
    genexpert_available: false,
    hiv_tb_integrated: true,
    pediatric_tb: false,
    drug_refill_days: "Wednesdays",
    contact_officer: "Nurse Grace",
    whatsapp_number: "2348012345617",
    facility_location_type: "Urban",
    status: "active",
  },
  {
    id: "18",
    clinic_name: "Amodu Alowomatana Health Centre",
    lga: "Sagamu",
    ward: "Itunsoku",
    town: "Sagamu",
    address: "Itunsoku Ward, Sagamu, Ogun State",
    latitude: 6.846502,
    longitude: 3.647329,
    phone: "08012345618",
    opening_hours: "Mon–Fri: 8:00am – 4:00pm",
    services: ["TB Screening", "DOT Treatment"],
    genexpert_available: false,
    hiv_tb_integrated: false,
    pediatric_tb: false,
    drug_refill_days: "Thursdays",
    contact_officer: "CHO Damilola",
    whatsapp_number: "2348012345618",
    facility_location_type: "Urban",
    status: "active",
  },
  {
    id: "19",
    clinic_name: "Isote Primary Health Centre",
    lga: "Sagamu",
    ward: "Isote",
    town: "Sagamu",
    address: "Isote Ward, Sagamu, Ogun State",
    latitude: 6.847996,
    longitude: 3.641809,
    phone: "08012345619",
    opening_hours: "Mon–Fri: 8:00am – 4:00pm",
    services: ["TB Screening", "DOT Treatment", "General OPD"],
    genexpert_available: false,
    hiv_tb_integrated: false,
    pediatric_tb: false,
    drug_refill_days: "Mondays",
    contact_officer: "Nurse Precious",
    whatsapp_number: "2348012345619",
    facility_location_type: "Urban",
    status: "active",
  },
  {
    id: "20",
    clinic_name: "Sotubo Health Centre",
    lga: "Sagamu",
    ward: "Ogijo",
    town: "Sotubo",
    address: "Sotubo, Ogijo, Sagamu LGA, Ogun State",
    latitude: 6.807533,
    longitude: 3.584403,
    phone: "08012345620",
    opening_hours: "Mon–Fri: 8:00am – 4:00pm",
    services: ["TB Screening", "DOT Treatment"],
    genexpert_available: false,
    hiv_tb_integrated: false,
    pediatric_tb: false,
    drug_refill_days: "Fridays",
    contact_officer: "CHO Rasheed",
    whatsapp_number: "2348012345620",
    facility_location_type: "Semi-Urban",
    status: "active",
  },
  {
    id: "21",
    clinic_name: "Simawa Primary Health Centre",
    lga: "Sagamu",
    ward: "Simawa",
    town: "Simawa",
    address: "Simawa, Sagamu LGA, Ogun State",
    latitude: 6.774019,
    longitude: 3.50171,
    phone: "08012345621",
    opening_hours: "Mon–Fri: 8:00am – 3:00pm",
    services: ["TB Screening", "DOT Treatment"],
    genexpert_available: false,
    hiv_tb_integrated: false,
    pediatric_tb: false,
    drug_refill_days: "Tuesdays",
    contact_officer: "Nurse Aminat",
    whatsapp_number: "2348012345621",
    facility_location_type: "Rural",
    status: "active",
  },
  {
    id: "22",
    clinic_name: "Likosi Primary Health Centre",
    lga: "Sagamu",
    ward: "Ogijo",
    town: "Likosi",
    address: "Likosi, Ogijo, Sagamu LGA, Ogun State",
    latitude: 6.761471,
    longitude: 3.536275,
    phone: "08012345622",
    opening_hours: "Mon–Fri: 8:00am – 4:00pm",
    services: ["TB Screening", "DOT Treatment"],
    genexpert_available: false,
    hiv_tb_integrated: false,
    pediatric_tb: false,
    drug_refill_days: "Wednesdays",
    contact_officer: "CHO Toyin",
    whatsapp_number: "2348012345622",
    facility_location_type: "Semi-Urban",
    status: "active",
  },
  {
    id: "23",
    clinic_name: "Owode Epota Health Centre",
    lga: "Sagamu",
    ward: "Sabo Agura",
    town: "Sagamu",
    address: "Owode Epota, Sabo Agura, Sagamu, Ogun State",
    latitude: 6.822969,
    longitude: 3.633803,
    phone: "08012345623",
    opening_hours: "Mon–Fri: 8:00am – 4:00pm",
    services: ["TB Screening", "DOT Treatment", "General OPD"],
    genexpert_available: false,
    hiv_tb_integrated: false,
    pediatric_tb: false,
    drug_refill_days: "Mondays",
    contact_officer: "Nurse Victoria",
    whatsapp_number: "2348012345623",
    facility_location_type: "Urban",
    status: "active",
  },
  {
    id: "24",
    clinic_name: "Makun Ojumele Health Centre",
    lga: "Sagamu",
    ward: "Ojumele",
    town: "Sagamu",
    address: "Makun Ojumele, Sagamu, Ogun State",
    latitude: 6.849035,
    longitude: 3.630761,
    phone: "08012345624",
    opening_hours: "Mon–Fri: 8:00am – 4:00pm",
    services: ["TB Screening", "DOT Treatment", "HIV/TB Clinic"],
    genexpert_available: true,
    hiv_tb_integrated: true,
    pediatric_tb: true,
    drug_refill_days: "Tuesdays and Fridays",
    contact_officer: "Dr. Adeyemi",
    whatsapp_number: "2348012345624",
    facility_location_type: "Urban",
    status: "active",
  },
];
